// Code generated by mockery v2.36.1. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	domain "github.com/transaction-manager/internal/domain"
)

// CreateTransactionUseCase is an autogenerated mock type for the CreateTransactionUseCase type
type CreateTransactionUseCase struct {
	mock.Mock
}

// Run provides a mock function with given fields: ctx, transaction
func (_m *CreateTransactionUseCase) Run(ctx context.Context, transaction *domain.Transaction) (int64, error) {
	ret := _m.Called(ctx, transaction)

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Transaction) (int64, error)); ok {
		return rf(ctx, transaction)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Transaction) int64); ok {
		r0 = rf(ctx, transaction)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *domain.Transaction) error); ok {
		r1 = rf(ctx, transaction)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewCreateTransactionUseCase creates a new instance of CreateTransactionUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCreateTransactionUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *CreateTransactionUseCase {
	mock := &CreateTransactionUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
