BEGIN;

-- Create the operation_type table
CREATE TABLE IF NOT EXISTS operation_types (
    id SERIAL PRIMARY KEY,
    is_debit BOOLEAN NOT NULL,
    description VARCHAR(255) NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

COMMIT;