version: "3.1"

services:
  db:
    image: postgres:15.4-alpine
    restart: always
    environment:
      POSTGRES_DB: transaction-manager-db-dev
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    command: ["postgres", "-c", "log_statement=all"]
    ports:
      - "5432:5432/tcp"
  service:
    container_name: service
    build:
      context: ../../
      dockerfile: ./infra/docker/Dockerfile
    depends_on:
      - db
    env_file:
      - ../../.env.local
    ports:
      - "8080:8080"
    restart: always
    volumes:
      - ../../:/app
    networks:
      - default