version: "3.1"

services:
  db:
    image: postgres:15.4-alpine
    restart: always
    environment:
      POSTGRES_DB: transaction-manager-db-dev
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    command: ["postgres", "-c", "log_statement=all"]
    ports:
      - "5432:5432/tcp"
